-- Run this script in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  login text not null unique,
  email text not null unique,
  password text,
  password_hash text,
  mobile_number text not null,
  team_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  head_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.team_heads (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  head_login text not null,
  unique (team_id, head_login)
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  member_name text not null,
  unique (team_id, member_name)
);

create table if not exists public.money_collections (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  event_name text not null,
  member_name text not null,
  amount numeric(12, 2) not null check (amount > 0),
  date timestamptz not null default now()
);

create table if not exists public.interest_records (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  principal_amount numeric(12, 2) not null,
  interest_rate numeric(8, 4) not null,
  start_date date not null,
  end_date date not null,
  interest_amount numeric(12, 2) not null,
  total_amount numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.money_collections enable row level security;
alter table public.interest_records enable row level security;

-- Migrate an older installation that used a plaintext password column.
-- Existing plaintext passwords are converted to salted hashes before the
-- plaintext column is removed.
alter table public.users add column if not exists password_hash text;
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'users'
      and column_name = 'password'
  ) then
    update public.users
    set password_hash = 'sha256$' || salt || '$' || encode(digest(salt || ':' || password, 'sha256'), 'hex')
    from (
      select id, encode(gen_random_bytes(16), 'hex') as salt
      from public.users
      where password_hash is null and password is not null
    ) as generated_salts
    where public.users.id = generated_salts.id;
    alter table public.users drop column password;
  end if;
end $$;
alter table public.users alter column password_hash set not null;

-- The first head remains available in teams.head_name for compatibility.
insert into public.team_heads (team_id, head_login)
select id, head_name from public.teams
on conflict (team_id, head_login) do nothing;

-- The FastAPI server uses the service-role key, so it can access these tables.
-- Never expose SUPABASE_SERVICE_ROLE_KEY in browser code or GitHub.
